/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#0e21a0",
        "on-primary": "#f8f0e5",
        "primary-fixed": "#d0d8f5",
        "primary-fixed-dim": "#a8b5e8",
        "on-primary-fixed": "#000e30",
        "on-primary-fixed-variant": "#0a1a55",
        "primary-container": "#0d1e8e",
        "on-primary-container": "#d0d8f5",
        "secondary": "#e5ad23",
        "on-secondary": "#262626",
        "secondary-fixed": "#f5e5a5",
        "secondary-fixed-dim": "#e5ad23",
        "on-secondary-fixed": "#2a1800",
        "on-secondary-fixed-variant": "#5a3a00",
        "secondary-container": "#f5e5a5",
        "on-secondary-container": "#0e21a0",
        "tertiary": "#b07800",
        "on-tertiary": "#f8f0e5",
        "tertiary-container": "#7a5200",
        "on-tertiary-container": "#f5e5a5",
        "tertiary-fixed": "#d0d8f5",
        "tertiary-fixed-dim": "#a8b5e8",
        "on-tertiary-fixed": "#000e30",
        "on-tertiary-fixed-variant": "#0a1a55",
        "background": "#f8f0e5",
        "on-background": "#262626",
        "surface": "#f8f0e5",
        "surface-bright": "#fdf8f0",
        "surface-dim": "#e8dece",
        "surface-tint": "#0e21a0",
        "surface-variant": "#e8dece",
        "on-surface": "#262626",
        "on-surface-variant": "#504538",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fbf3ea",
        "surface-container": "#f2eadb",
        "surface-container-high": "#ece3d3",
        "surface-container-highest": "#e5dbcc",
        "outline": "#8a7a6a",
        "outline-variant": "#d8ccba",
        "inverse-surface": "#262626",
        "inverse-on-surface": "#f8f0e5",
        "inverse-primary": "#e5ad23",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "section-padding": "80px",
        "base": "8px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      fontFamily: {
        "label-md": ["Montserrat"],
        "headline-lg": ["Lora"],
        "body-lg": ["Montserrat"],
        "headline-md": ["Lora"],
        "body-md": ["Montserrat"],
        "headline-xl": ["Lora"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
